### PR TITLE
kitties tutorial: fix sp_io import

### PR DESCRIPTION
**Pull request by bernardoaraujor**
importing `sp_io::hashing::blake2_128` needs to happend inside `frame_support`.
all the template files were importing outside, which generates
```
error[E0433]: failed to resolve: use of undeclared crate or module `sp_io`
  --> pallets/kitties/src/lib.rs:12:9
   |
12 |     use sp_io::hashing::blake2_128;
   |         ^^^^^ use of undeclared crate or module `sp_io`
```

### CODE REVIEW

**Comment by NukeManDan** [comment]
@bernardoaraujor - can this be propagated to main-md? @sacha-l please review :)

**Comment by sacha-l** [comment]
Thanks for looking into this. `sp_io` is not a crate in `frame_support` - I may be missing something but this wouldn't compile as is. 

The fix here is to tell users that they need to go and change the `Cargo.toml` file to specify that `sp_io` will be required in the pallet's `[dependencies]` (in `pallets/pallet/Cargo.toml` for example):

```toml
[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
frame-support = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23"}
frame-system = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
frame-benchmarking = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23", optional = true }
sp-io = { default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-runtime = { default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
pallet-randomness-collective-flip = { default-features = false, version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.23" }
pallet-balances = { default-features = false, version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.23" }
```

A node template out of the box usually has `sp_io` in `[dev-dependencies]` so all users need to do is move it out of there and into `[dependencies]`. Step 2 of [this section](https://docs.substrate.io/tutorials/v3/kitties/pt1/#write-the-pallet_kitties-scaffold) stipulates this. Perhaps it's not clear enough and we can be more explicit about "why and what" this is about.

**Comment by bernardoaraujor** [comment]
indeed, my PR is going in a wrong direction. I was actually just missing the step 2.

doing these changes does get the code to compile, most likely because `sp_io` [is re-exported](https://github.com/paritytech/substrate/blob/b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4/frame/support/src/lib.rs#L47) by `frame_support`.
regardless, that's not the proper way to do it.

I'll just send another PR clarifying `[dependencies]` vs `[dev-dependencies]`.
sorry for the noise.

**Comment by bernardoaraujor** [comment]
@NukeManDan @sacha-l is kitties not included in `main-md`?
I can't seem to find it.

**Pull request closed without merging**
