### PR TITLE
Lg/contracts ink workshop

### PR DESCRIPTION
**Pull request by lisa-parity**
This PR pushes the content revisions (text) for "part 1" of the smart contract/ink tutorial using the material from the `main-md` branch where the information architecture overhaul is happening. Since this is going to the live site, it should have some eyes on it and some sanity checking.
The full revision is here:
https://github.com/substrate-developer-hub/substrate-docs/pull/899

### CODE REVIEW

**Comment by lisa-parity** [comment]
@HCastano, thanks for letting me know who should review these PRs!
https://github.com/substrate-developer-hub/substrate-docs/pull/899 is a rewrite of all three sections for our revamped version of the docs site. The navigation is a bit different, so I ported the revised content into this PR.
Currently, these three tutorials are all slightly broken and the code in the assets/tutorials/ink-workshop doesn't compile.
I created new versions for the revision but didn't want to touch non-docs repos.
I'll add the reviewers you suggest to the other PR. If the rewrite is approved, then I'll bring the changes into the main branch.

**Comment by cmichi** [comment]
@lisa-parity Do I understand you right that we should only review https://github.com/substrate-developer-hub/substrate-docs/pull/899 and there's no need to review this PR?

**Comment by lisa-parity** [comment]
@cmichi , Thanks so much for taking the time to review [899](https://github.com/substrate-developer-hub/substrate-docs/pull/899)! You are correct -- no need to review this one. I'll port the changes to this PR so we can go live while the new doc site is still under development.
I think we need to swap out some of the template and solution code but they are in a different repo.
Thanks again.

**Comment by lisa-parity** [comment]
@cmichi , Thanks so much for taking the time to review [899](https://github.com/substrate-developer-hub/substrate-docs/pull/899)! You are correct -- no need to review this one. I'll port the changes to this PR so we can go live while the new doc site is still under development.
I think we need to swap out some of the template and solution code but they are in a different repo.
Thanks again.

**Pull request merged**
