### PR TITLE
Lg/pallet scheduler upgrade runtime

### PR DESCRIPTION
**Pull request by lisa-parity**
Update the upgrade tutorial to work with new weights and traits for branch = "polkadot-v0.9.35"

### CODE REVIEW

**Comment by lisa-parity** [comment]
@ggwpez 
In case you get a chance to take a look. I added the Scheduler pallet with the new traits and one of the Weight definitions that compiled in 0.9.32 but doesn't compile in 0.9.35.
The main errors seem to be:
```
the trait `Decode` | `Encode`is not implemented for `sp_runtime::generic::UncheckedExtrinsic<MultiAddress<AccountId32, ()>, RuntimeCall, MultiSignature, (CheckNonZeroSender<Runtime>, CheckSpecVersion<Runtime>, CheckTxVersion<Runtime>, CheckGenesis<Runtime>, CheckEra<Runtime>, CheckNonce<Runtime>, CheckWeight<Runtime>, ChargeTransactionPayment<Runtime>)>
```

and

```
^ within `RuntimeCall`, the trait `Callable<Runtime>` is not implemented for `pallet_scheduler::Pallet<Runtime>`
```

But I haven't been albe to find where to make the fix.

[Cargo.toml.txt](https://github.com/substrate-developer-hub/substrate-docs/files/10272125/Cargo.toml.txt)
[lib.rs.txt](https://github.com/substrate-developer-hub/substrate-docs/files/10272128/lib.rs.txt)

**Comment by ggwpez** [comment]
> In case you get a chance to take a look. I added the Scheduler pallet with the new traits and one of the Weight definitions that compiled in 0.9.32 but doesn't compile in 0.9.35.

Hi @lisa-parity! Just seeing it now.  
Could you please push the code directly as a branch here https://github.com/substrate-developer-hub/substrate-node-template/ ?  
I get a different error when I try it out, so would be good to have the code directly instead of patching it manually :smile:

**Comment by lisa-parity** [comment]
It looks like I don't have permission to push to that repo:
git push origin LG/wip-node-template 
remote: Permission to substrate-developer-hub/substrate-node-template.git denied to lisa-parity.
fatal: unable to access 'https://github.com/substrate-developer-hub/substrate-node-template.git/': The requested URL returned error: 403

**Comment by l0r1s** [comment]
Hi,
I had the same problems to compile, ended up setting:

`
type WeightInfo = ();
type Preimages = ();
`

Given `WeightInfo`, `QueryPreImage + StorePreImage`  are implemented for ()

Now it compiles but I can't schedule upgrade, having an `exhausted` error.

**Comment by ggwpez** [comment]
>It looks like I don't have permission to push to that repo:

Okay… Is the finished code of the tutorial somewhere to be found? So that users who cant make it will have a proper solution to compare to?

**Pull request merged**
