### PR TITLE
[docs] Update missing link

### PR DESCRIPTION
**Pull request by brunopgalvao**
not sure what the link should be...

### CODE REVIEW

**Review by NukeManDan — APPROVED** [review]
good addition, thanks!

**Comment by NukeManDan** [comment]
image

I have double checked locally links are fine. #552 
We are good to merge this as is

**Comment by sacha-l** [comment]
> image
> 
> I have double checked locally links are fine. #552 We are good to merge this as is https://github.com/substrate-developer-hub/substrate-docs/runs/4234665352?check_suite_focus=true docker login is broken? 😕 cc @imadarai

The Docker login error still hasn't been fixed. But we can ignore it for now. Looks like there's a merge conflict though, @NukeManDan you good to fix it and merge?  🙏🏻

**Comment by brunopgalvao** [comment]
Merge resolved. Needs approval.

**Comment by imadarai** [comment]
@sacha-l @NukeManDan 
Just a reminder that Docker image doesn't work for outside contributors, as the login/pass are internal secrets.  
I just got the access to docker vault today so will look further into this when back.

**Pull request merged**
