### PR TITLE
StackExchange Campaign Banner

### PR DESCRIPTION
**Pull request by je-boska**

### CODE REVIEW

**Review by NukeManDan — APPROVED** [review]
LGTM 
image

**Comment by NukeManDan** [comment]
I actually wanted to emphasize this more, so I inverted the color scheme and changed the text a bit. Hope you like it? 
image
image

**Review by imadarai — APPROVED** [review]
@je-boska Looks good to me! 

I would say I liked the inverted color changes proposed by Dan.  But go ahead with whatever was approved by Roman/Patrick.  Feel free to revert the changes and merge.

**Comment by je-boska** [comment]
@imadarai Great! I have approval to align the IO stack to this version, so you can go ahead and merge this PR (I'm not authorized).

**Pull request merged**
