### PR TITLE
Fix substrate-node-temple update tutorial  can't compile

### PR DESCRIPTION
**Pull request by noobHuKai**
Fix substrate-node-temple update but tutorial can't compile

### CODE REVIEW

**Comment by lisa-parity** [comment]
Hi @noobHuKai,

1. Check that you are using the` substrate-node-template `from the Developer Hub.
2. Make sure you have checked out the latest branch.
3. Check what the dependencies look like for other pallets.
4. Add the new pallet using the same version, repo, and branch as the the pallets.

   For example, if the other pallets use `4.0.0-dev` and polkadot `v0.9.23`, so should yours:
   `pallet-nicks = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
`

After you make the changes, run:
   `cargo check -p node-template-runtime
`to verify that it compiles (it did for me).
I'm going to close this PR and made fixes in a separate PR. Thanks so much for catching this bit of old stuff!

**Comment by noobHuKai** [comment]
Sorry, I think the tutorial had better be right,
Adding dependencies according to the tutorial happen:
```
error: failed to select a version for `parity-util-mem`.
    ... required by package `sp-runtime v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)`
    ... which satisfies git dependency `sp-runtime` of package `frame-support v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)`
    ... which satisfies git dependency `frame-support` of package `frame-system v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)`
    ... which satisfies git dependency `frame-system` of package `pallet-nicks v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)`
    ... which satisfies git dependency `pallet-nicks` of package `node-template-runtime v4.0.0-dev (/home/Study/BlockchainStudy/SubstrateStudy/substrate-node-template/runtime)`
    ... which satisfies path dependency `node-template-runtime` of package `node-template v4.0.0-dev (/home/Study/BlockchainStudy/SubstrateStudy/substrate-node-template/node)`
versions that meet the requirements `^0.10.0` are: 0.10.2, 0.10.1, 0.10.0

the package `parity-util-mem` links to the native library `parity-util-mem-ban-duplicates`, but it conflicts with a previous package which links to `parity-util-mem-ban-duplicates` as well:
package `parity-util-mem v0.11.0`
    ... which satisfies dependency `parity-util-mem = "^0.11"` of package `kvdb v0.11.0`
    ... which satisfies dependency `kvdb = "^0.11.0"` of package `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.24#814752f6)`
    ... which satisfies git dependency `frame-benchmarking-cli` of package `node-template v4.0.0-dev (/home/Study/BlockchainStudy/SubstrateStudy/substrate-node-template/node)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='parity-util-mem' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `parity-util-mem` which could resolve this conflict
```

**Comment by lisa-parity** [comment]
Is this the contracts tutorial? If so, yeah, I've run into issues there too. working on it!

**Comment by lisa-parity** [comment]
Thanks for testing and helping us improve!

**Pull request closed without merging**
