### PR TITLE
Update simulate-parachains.md

### PR DESCRIPTION
**Pull request by brunopgalvao**
Update for PBA!

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]
Thanks @brunopgalvao!

**Comment by brunopgalvao** [comment]
@lisa-parity this is bumping the version to `0.9.37` and has minor updates to the zombienet config.

**Comment by NukeManDan** [comment]
@lisa-parity good time to update all parachain content, as the present docs are quite out of date. Should only be minor things to tweak throughout.

**Review by lisa-parity — APPROVED** [review]

**Comment by NukeManDan** [comment]
Sorry if it was not clear, i think this info update does not work with the other parachain content using 0.9.32. as the versions are too old. Is that the case @brunopgalvao ?

If so this pr should be reverted imho, because its a footgun for users to fight with version mismatches and usually they don't find that is the problem without substantial headache first.

**Pull request merged**
