### PR TITLE
Fix Home page scrolling issues

### PR DESCRIPTION
**Pull request by je-boska**
Notion: https://www.notion.so/paritytechnologies/Docs-Home-horizontal-scrolling-dc5847c3e92742749cfb6dd5a726db66

### CODE REVIEW

**Comment by je-boska** [comment]
The only difference in the way this appears from what's currently deployed, is that the browser mockup in the Playground section now fades in from the right starting at the container width, rather than all the way from the right of the view.

**Review by NukeManDan — APPROVED** [review]
Trust this is fine, @je-boska is all you needed and approval? If so, please just ping on element when you need this, or request a review from me or any other admin

**Comment by rmnprkrl** [comment]
@je-boska 
it is caused by this AOS transition:

image

Adding `overflow-hidden` to the wrapper like shown in the screenshot should be enough to fix it..

**Comment by je-boska** [comment]
> @je-boska it is caused by this AOS transition:
> 
> image
> 
> Adding `overflow-hidden` to the wrapper like shown in the screenshot should be enough to fix it..

Yes, I added overflow-x-hidden to the wrapper of that asset.

There were fixed widths on some of the cards in the section above, which was also causing some minor horizontal scrolling. I sorted this by placing them in a grid instead. There is a visible difference in how they appear, but it's very minor.

**Comment by rmnprkrl** [comment]
@je-boska could you test it doesn't break anything when added to to the main container instead?:
`<main class="main-container overflow-x-hidden">`

Adding only to that AOS wrapper as I suggested crops the transition visually..

**Comment by je-boska** [comment]
I can't find any problems with adding it to the `main-container` class. Let me know if it's OK to edit the `tailwind-preset.css` file in this case.

I also fixed vertical scrolling caused by overflow on the section above ("Learn Substrate").

**Comment by rmnprkrl** [comment]
Everything needs to stay in tailwind (or particular used framework in general) context, only if not possible it goes out of the system, add it to the container directly

> I can't find any problems with adding it to the main-container class

did you you test it does not break any page on any break point on VA devices?

**Comment by je-boska** [comment]
Tested on mac and iOS, across Chrome/Brave, Safari and Firefox. Couldn't find any breakage.

**Comment by rmnprkrl** [comment]
LGTM

**Pull request merged**
